#! /usr/bin/env python
# encoding: utf-8
# Oliver Sauder, 2010

import os

task = bld.new_task_gen(
  features = 'py',
  source = bld.path.ant_glob('*.py'),
  install_path = os.path.join(bld.env['PLUGINS_DIR'], 'clipperplus'))

bld.install_files(task.install_path, 'clipperplus.plugin')

